apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    {{ include "wordpress.applabels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
      name: wordpress  
  selector:
    {{ include "wordpress.applabels" . | indent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    {{ include "wordpress.mysqllabels" . | indent 4 }}
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    {{ include "wordpress.mysqllabels" . | indent 4 }}
