apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: wordpress
    app.kubernetes.io/name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: wordpress
    tier: mysql
